on:
  schedule:
    - cron: '0 1 * * *'  # Exécution quotidienne à 1h du matin
  workflow_dispatch:     # Permet l'exécution manuelle

jobs:
  generate-invoices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run invoice generator
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          SELLSY_CLIENT_ID: ${{ secrets.SELLSY_CLIENT_ID }}
          SELLSY_CLIENT_SECRET: ${{ secrets.SELLSY_CLIENT_SECRET }}
        run: node src/index.js
